[package]
name = "cetrizine"
version = "1.0.1-wip"
authors = ["Shelvacu <shelvacu@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "*"
time = "*"
r2d2_postgres = "*"
argparse = "~0.2"
postgres-derive = "*"
pbr = "*"
backtrace = "0.3"

[dependencies.rusqlite]
version = "~0.18.0"
features = ["chrono","unlock_notify","bundled"]

[dependencies.postgres]
version = "~0.15.2"
features = ["with-serde_json","with-time","with-chrono"]

[dependencies.serenity]
version = "0.5.14-shel1"
path = "../serenity/"
default-features = true
features = ["raw-ws-event"]