[package]
name = "cetrizine"
version = "1.0.0-wip"
authors = ["Shelvacu <shelvacu@gmail.com>"]
edition = "2018"

[dependencies]
serenity = { version = "0.5.13", path = "../serenity/", default-features = true }
chrono = "*"
time = "*"
r2d2_postgres = "*"
argparse = "~0.2"
postgres-derive = "*"
pbr = "*"

[dependencies.rusqlite]
version = "~0.18.0"
features = ["chrono","unlock_notify","bundled"]

[dependencies.postgres]
version = "~0.15.2"
features = ["with-serde_json","with-time","with-chrono"]