[package]
name = "cetrizine"
version = "0.2.0"
authors = ["Shelvacu <shelvacu@gmail.com>"]
edition = "2018"

[dependencies]
serenity = { version = "0.5.13", path = "../serenity/", default-features = true }
chrono = "*"
time = "*"

[dependencies.rusqlite]
version = "~0.18.0"
features = ["chrono","unlock_notify","bundled"]