
table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `attachment` table.
    ///
    /// (Automatically generated by Diesel.)
    attachment (rowid) {
        /// The `rowid` column of the `attachment` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `message_rowid` column of the `attachment` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        message_rowid -> Int8,
        /// The `discord_id` column of the `attachment` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        discord_id -> SQL_Snowflake,
        /// The `filename` column of the `attachment` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        filename -> Text,
        /// The `height` column of the `attachment` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        height -> Nullable<Int8>,
        /// The `width` column of the `attachment` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        width -> Nullable<Int8>,
        /// The `proxy_url` column of the `attachment` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        proxy_url -> Text,
        /// The `size` column of the `attachment` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        size -> Int8,
        /// The `url` column of the `attachment` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        url -> Text,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `embed` table.
    ///
    /// (Automatically generated by Diesel.)
    embed (rowid) {
        /// The `rowid` column of the `embed` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `message_rowid` column of the `embed` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        message_rowid -> Int8,
        /// The `author` column of the `embed` table.
        ///
        /// Its SQL type is `Nullable<Array<_t_embed_author>>`.
        ///
        /// (Automatically generated by Diesel.)
        author -> Nullable<SQL_EmbedAuthor>,
        /// The `colour_u32` column of the `embed` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        colour_u32 -> Nullable<SQL_DiscordColour>,
        /// The `description` column of the `embed` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `footer` column of the `embed` table.
        ///
        /// Its SQL type is `Nullable<Array<_t_embed_footer>>`.
        ///
        /// (Automatically generated by Diesel.)
        footer -> Nullable<SQL_EmbedFooter>,
        /// The `image` column of the `embed` table.
        ///
        /// Its SQL type is `Nullable<Array<_t_embed_image>>`.
        ///
        /// (Automatically generated by Diesel.)
        image -> Nullable<SQL_EmbedImage>,
        /// The `kind` column of the `embed` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        kind -> Text,
        /// The `provider` column of the `embed` table.
        ///
        /// Its SQL type is `Nullable<Array<_t_embed_provider>>`.
        ///
        /// (Automatically generated by Diesel.)
        provider -> Nullable<SQL_EmbedProvider>,
        /// The `thumbnail` column of the `embed` table.
        ///
        /// Its SQL type is `Nullable<Array<_t_embed_image>>`.
        ///
        /// (Automatically generated by Diesel.)
        thumbnail -> Nullable<SQL_EmbedImage>,
        /// The `timestamp` column of the `embed` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Nullable<Text>,
        /// The `title` column of the `embed` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Nullable<Text>,
        /// The `url` column of the `embed` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        url -> Nullable<Text>,
        /// The `video` column of the `embed` table.
        ///
        /// Its SQL type is `Nullable<Array<_t_embed_video>>`.
        ///
        /// (Automatically generated by Diesel.)
        video -> Nullable<SQL_EmbedVideo>,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `embed_field` table.
    ///
    /// (Automatically generated by Diesel.)
    embed_field (rowid) {
        /// The `rowid` column of the `embed_field` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `embed_rowid` column of the `embed_field` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        embed_rowid -> Int8,
        /// The `inline` column of the `embed_field` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        inline -> Bool,
        /// The `name` column of the `embed_field` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `value` column of the `embed_field` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `emoji` table.
    ///
    /// (Automatically generated by Diesel.)
    emoji (rowid) {
        /// The `rowid` column of the `emoji` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `guild_rowid` column of the `emoji` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_rowid -> Int8,
        /// The `discord_id` column of the `emoji` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        discord_id -> SQL_Snowflake,
        /// The `animated` column of the `emoji` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        animated -> Bool,
        /// The `name` column of the `emoji` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `managed` column of the `emoji` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        managed -> Bool,
        /// The `require_colons` column of the `emoji` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        require_colons -> Bool,
        /// The `roles` column of the `emoji` table.
        ///
        /// Its SQL type is `Array<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        roles -> Array<SQL_Snowflake>,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `group_channel` table.
    ///
    /// (Automatically generated by Diesel.)
    group_channel (rowid) {
        /// The `rowid` column of the `group_channel` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `ready_rowid` column of the `group_channel` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        ready_rowid -> Int8,
        /// The `discord_id` column of the `group_channel` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        discord_id -> SQL_Snowflake,
        /// The `icon` column of the `group_channel` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        icon -> Nullable<Text>,
        /// The `last_message_id` column of the `group_channel` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        last_message_id -> Nullable<SQL_Snowflake>,
        /// The `last_pin_timestamp` column of the `group_channel` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_pin_timestamp -> Nullable<Timestamptz>,
        /// The `name` column of the `group_channel` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Nullable<Text>,
        /// The `owner_id` column of the `group_channel` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        owner_id -> SQL_Snowflake,
        /// The `recipients` column of the `group_channel` table.
        ///
        /// Its SQL type is `Array<Discord_user>`.
        ///
        /// (Automatically generated by Diesel.)
        recipients -> Array<SQL_DiscordUser>,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `guild` table.
    ///
    /// (Automatically generated by Diesel.)
    guild (rowid) {
        /// The `rowid` column of the `guild` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `ready_rowid` column of the `guild` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        ready_rowid -> Nullable<Int8>,
        /// The `discord_id` column of the `guild` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        discord_id -> SQL_Snowflake,
        /// The `afk_channel_id` column of the `guild` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        afk_channel_id -> Nullable<SQL_Snowflake>,
        /// The `afk_timeout` column of the `guild` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        afk_timeout -> Nullable<Int8>,
        /// The `application_id` column of the `guild` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        application_id -> Nullable<Int8>,
        /// The `default_message_notification_level` column of the `guild` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        default_message_notification_level -> Text,
        /// The `explicit_content_filter` column of the `guild` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        explicit_content_filter -> Text,
        /// The `features` column of the `guild` table.
        ///
        /// Its SQL type is `Array<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        features -> Array<Text>,
        /// The `icon` column of the `guild` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        icon -> Nullable<Text>,
        /// The `joined_at` column of the `guild` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        joined_at -> Nullable<Timestamptz>,
        /// The `large` column of the `guild` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        large -> Bool,
        /// The `member_count` column of the `guild` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        member_count -> Int8,
        /// The `mfa_level` column of the `guild` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        mfa_level -> Text,
        /// The `name` column of the `guild` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `owner_id` column of the `guild` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        owner_id -> SQL_Snowflake,
        /// The `region` column of the `guild` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        region -> Text,
        /// The `splash` column of the `guild` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        splash -> Nullable<Text>,
        /// The `system_channel_id` column of the `guild` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        system_channel_id -> Nullable<SQL_Snowflake>,
        /// The `verification_level` column of the `guild` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        verification_level -> Text,
        /// The `archive_recvd_at` column of the `guild` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        archive_recvd_at -> Timestamptz,
        /// The `guild_create_event_rowid` column of the `guild` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        guild_create_event_rowid -> Nullable<Int8>,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `guild_channel` table.
    ///
    /// (Automatically generated by Diesel.)
    guild_channel (rowid) {
        /// The `rowid` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `discord_id` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        discord_id -> SQL_Snowflake,
        /// The `guild_rowid` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        guild_rowid -> Nullable<Int8>,
        /// The `bitrate` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        bitrate -> Nullable<Int8>,
        /// The `category_id` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        category_id -> Nullable<SQL_Snowflake>,
        /// The `guild_id` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_id -> SQL_Snowflake,
        /// The `kind` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        kind -> Text,
        /// The `last_message_id` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        last_message_id -> Nullable<SQL_Snowflake>,
        /// The `last_pin_timestamp` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_pin_timestamp -> Nullable<Timestamptz>,
        /// The `name` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `position` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        position -> Int8,
        /// The `topic` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        topic -> Nullable<Text>,
        /// The `user_limit` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        user_limit -> Nullable<Int8>,
        /// The `nsfw` column of the `guild_channel` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        nsfw -> Bool,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `guild_create_event` table.
    ///
    /// (Automatically generated by Diesel.)
    guild_create_event (rowid) {
        /// The `rowid` column of the `guild_create_event` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `is_new` column of the `guild_create_event` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_new -> Bool,
        /// The `recvd_at_datetime` column of the `guild_create_event` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        recvd_at_datetime -> Timestamptz,
        /// The `recvd_at_duration_secs` column of the `guild_create_event` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        recvd_at_duration_secs -> Int8,
        /// The `recvd_at_duration_nanos` column of the `guild_create_event` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        recvd_at_duration_nanos -> Int4,
        /// The `session_rowid` column of the `guild_create_event` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        session_rowid -> Int8,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `guild_prefixes` table.
    ///
    /// (Automatically generated by Diesel.)
    guild_prefixes (guild_id) {
        /// The `guild_id` column of the `guild_prefixes` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_id -> SQL_Snowflake,
        /// The `command_prefix` column of the `guild_prefixes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        command_prefix -> Text,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `guild_role` table.
    ///
    /// (Automatically generated by Diesel.)
    guild_role (rowid) {
        /// The `rowid` column of the `guild_role` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `guild_rowid` column of the `guild_role` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_rowid -> Int8,
        /// The `discord_id` column of the `guild_role` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        discord_id -> SQL_Snowflake,
        /// The `colour_u32` column of the `guild_role` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        colour_u32 -> Nullable<Int8>,
        /// The `hoist` column of the `guild_role` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        hoist -> Bool,
        /// The `managed` column of the `guild_role` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        managed -> Bool,
        /// The `mentionable` column of the `guild_role` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        mentionable -> Bool,
        /// The `name` column of the `guild_role` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `permissions_bits` column of the `guild_role` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        permissions_bits -> Int8,
        /// The `position` column of the `guild_role` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        position -> Int8,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `log_entry` table.
    ///
    /// (Automatically generated by Diesel.)
    log_entry (rowid) {
        /// The `rowid` column of the `log_entry` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `logged_at_datetime` column of the `log_entry` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        logged_at_datetime -> Timestamptz,
        /// The `logged_at_duration_secs` column of the `log_entry` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        logged_at_duration_secs -> Int8,
        /// The `logged_at_duration_nanos` column of the `log_entry` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        logged_at_duration_nanos -> Int4,
        /// The `session_rowid` column of the `log_entry` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        session_rowid -> Int8,
        /// The `log_level` column of the `log_entry` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        log_level -> Text,
        /// The `target` column of the `log_entry` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        target -> Text,
        /// The `module_path` column of the `log_entry` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        module_path -> Nullable<Text>,
        /// The `file` column of the `log_entry` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        file -> Nullable<Text>,
        /// The `line` column of the `log_entry` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        line -> Nullable<Int8>,
        /// The `message_body` column of the `log_entry` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        message_body -> Text,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `member` table.
    ///
    /// (Automatically generated by Diesel.)
    member (rowid) {
        /// The `rowid` column of the `member` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `guild_rowid` column of the `member` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_rowid -> Int8,
        /// The `guild_id` column of the `member` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_id -> SQL_Snowflake,
        /// The `deaf` column of the `member` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        deaf -> Bool,
        /// The `joined_at` column of the `member` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        joined_at -> Nullable<Timestamptz>,
        /// The `mute` column of the `member` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        mute -> Bool,
        /// The `nick` column of the `member` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        nick -> Nullable<Text>,
        /// The `roles` column of the `member` table.
        ///
        /// Its SQL type is `Array<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        roles -> Array<SQL_Snowflake>,
        /// The `user_info` column of the `member` table.
        ///
        /// Its SQL type is `Array<_t_discord_user>`.
        ///
        /// (Automatically generated by Diesel.)
        user_info -> SQL_DiscordUser,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `message` table.
    ///
    /// (Automatically generated by Diesel.)
    message (rowid) {
        /// The `rowid` column of the `message` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `discord_id` column of the `message` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        discord_id -> SQL_Snowflake,
        /// The `author` column of the `message` table.
        ///
        /// Its SQL type is `Array<_t_discord_user>`.
        ///
        /// (Automatically generated by Diesel.)
        author -> SQL_DiscordUser,
        /// The `channel_id` column of the `message` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        channel_id -> SQL_Snowflake,
        /// The `content` column of the `message` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        content -> Text,
        /// The `edited_timestamp` column of the `message` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        edited_timestamp -> Nullable<Timestamptz>,
        /// The `guild_id` column of the `message` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        guild_id -> Nullable<SQL_Snowflake>,
        /// The `kind` column of the `message` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        kind -> Nullable<Text>,
        /// The `member` column of the `message` table.
        ///
        /// Its SQL type is `Nullable<Array<_t_partial_member>>`.
        ///
        /// (Automatically generated by Diesel.)
        member -> Nullable<SQL_PartialMember>,
        /// The `mention_everyone` column of the `message` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        mention_everyone -> Bool,
        /// The `mention_roles` column of the `message` table.
        ///
        /// Its SQL type is `Array<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        mention_roles -> Array<SQL_Snowflake>,
        /// The `mentions` column of the `message` table.
        ///
        /// Its SQL type is `Array<Discord_user>`.
        ///
        /// (Automatically generated by Diesel.)
        mentions -> Array<SQL_DiscordUser>,
        /// The `nonce_debug` column of the `message` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        nonce_debug -> Text,
        /// The `pinned` column of the `message` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        pinned -> Bool,
        /// The `timestamp` column of the `message` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Timestamptz,
        /// The `tts` column of the `message` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        tts -> Bool,
        /// The `webhook_id` column of the `message` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        webhook_id -> Nullable<SQL_Snowflake>,
        /// The `archive_recvd_at` column of the `message` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        archive_recvd_at -> Timestamptz,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `message_archive_gets` table.
    ///
    /// (Automatically generated by Diesel.)
    message_archive_gets (rowid) {
        /// The `rowid` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `channel_id` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        channel_id -> SQL_Snowflake,
        /// The `ready_rowid` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        ready_rowid -> Nullable<Int8>,
        /// The `after_message_id` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        after_message_id -> Nullable<SQL_Snowflake>,
        /// The `around_message_id` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        around_message_id -> Nullable<SQL_Snowflake>,
        /// The `before_message_id` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        before_message_id -> Nullable<SQL_Snowflake>,
        /// The `start_message_id` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        start_message_id -> Nullable<SQL_Snowflake>,
        /// The `end_message_id` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        end_message_id -> Nullable<SQL_Snowflake>,
        /// The `message_count_requested` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        message_count_requested -> Nullable<Int8>,
        /// The `message_count_received` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        message_count_received -> Nullable<Int8>,
        /// The `legacy` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        legacy -> Bool,
        /// The `synthetic` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        synthetic -> Bool,
        /// The `finished` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        finished -> Bool,
        /// The `session_id` column of the `message_archive_gets` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        session_id -> Nullable<Int8>,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `migration_version` table.
    ///
    /// (Automatically generated by Diesel.)
    migration_version (enforce_single_row) {
        /// The `version` column of the `migration_version` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Int8,
        /// The `enforce_single_row` column of the `migration_version` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        enforce_single_row -> Bool,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `permission_overwrite` table.
    ///
    /// (Automatically generated by Diesel.)
    permission_overwrite (rowid) {
        /// The `rowid` column of the `permission_overwrite` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `guild_channel_rowid` column of the `permission_overwrite` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_channel_rowid -> Int8,
        /// The `allow_bits` column of the `permission_overwrite` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        allow_bits -> Int8,
        /// The `deny_bits` column of the `permission_overwrite` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        deny_bits -> Int8,
        /// The `permission_overwrite_type` column of the `permission_overwrite` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        permission_overwrite_type -> Text,
        /// The `permission_overwrite_id` column of the `permission_overwrite` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        permission_overwrite_id -> SQL_Snowflake,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `private_channel` table.
    ///
    /// (Automatically generated by Diesel.)
    private_channel (rowid) {
        /// The `rowid` column of the `private_channel` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `ready_rowid` column of the `private_channel` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        ready_rowid -> Int8,
        /// The `discord_id` column of the `private_channel` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        discord_id -> SQL_Snowflake,
        /// The `last_message_id` column of the `private_channel` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        last_message_id -> Nullable<SQL_Snowflake>,
        /// The `last_pin_timestamp` column of the `private_channel` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_pin_timestamp -> Nullable<Timestamptz>,
        /// The `kind` column of the `private_channel` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        kind -> Text,
        /// The `recipient` column of the `private_channel` table.
        ///
        /// Its SQL type is `Array<_t_discord_user>`.
        ///
        /// (Automatically generated by Diesel.)
        recipient -> SQL_DiscordUser,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `raw_message` table.
    ///
    /// (Automatically generated by Diesel.)
    raw_message (rowid) {
        /// The `rowid` column of the `raw_message` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `recvd_at_datetime` column of the `raw_message` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        recvd_at_datetime -> Timestamptz,
        /// The `recvd_at_duration_secs` column of the `raw_message` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        recvd_at_duration_secs -> Int8,
        /// The `recvd_at_duration_nanos` column of the `raw_message` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        recvd_at_duration_nanos -> Int4,
        /// The `session_rowid` column of the `raw_message` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        session_rowid -> Int8,
        /// The `kind` column of the `raw_message` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        kind -> Text,
        /// The `content_text` column of the `raw_message` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        content_text -> Nullable<Text>,
        /// The `content_binary` column of the `raw_message` table.
        ///
        /// Its SQL type is `Nullable<Bytea>`.
        ///
        /// (Automatically generated by Diesel.)
        content_binary -> Nullable<Bytea>,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `reaction` table.
    ///
    /// (Automatically generated by Diesel.)
    reaction (rowid) {
        /// The `rowid` column of the `reaction` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `message_rowid` column of the `reaction` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        message_rowid -> Int8,
        /// The `count` column of the `reaction` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        count -> Int8,
        /// The `me` column of the `reaction` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        me -> Bool,
        /// The `reaction_is_custom` column of the `reaction` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        reaction_is_custom -> Bool,
        /// The `reaction_animated` column of the `reaction` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        reaction_animated -> Nullable<Bool>,
        /// The `reaction_id` column of the `reaction` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        reaction_id -> Nullable<SQL_Snowflake>,
        /// The `reaction_name` column of the `reaction` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        reaction_name -> Nullable<Text>,
        /// The `reaction_string` column of the `reaction` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        reaction_string -> Nullable<Text>,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `ready` table.
    ///
    /// (Automatically generated by Diesel.)
    ready (rowid) {
        /// The `rowid` column of the `ready` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `session_id` column of the `ready` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        session_id -> Text,
        /// The `shard` column of the `ready` table.
        ///
        /// Its SQL type is `Nullable<Array<Int8>>`.
        ///
        /// (Automatically generated by Diesel.)
        shard -> Nullable<Array<Int8>>,
        /// The `trace` column of the `ready` table.
        ///
        /// Its SQL type is `Array<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        trace -> Array<Text>,
        /// The `user_info` column of the `ready` table.
        ///
        /// Its SQL type is `Array<_t_serenity_current_user>`.
        ///
        /// (Automatically generated by Diesel.)
        user_info -> Array<SQL_SerenityCurrentUser>,
        /// The `version` column of the `ready` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Int8,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `run_session` table.
    ///
    /// (Automatically generated by Diesel.)
    run_session (rowid) {
        /// The `rowid` column of the `run_session` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `started_at` column of the `run_session` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        started_at -> Timestamptz,
        /// The `pkg_name` column of the `run_session` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        pkg_name -> Nullable<Text>,
        /// The `version` column of the `run_session` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Nullable<Text>,
        /// The `target` column of the `run_session` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        target -> Nullable<Text>,
        /// The `build_timestamp` column of the `run_session` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        build_timestamp -> Nullable<Text>,
        /// The `git_sha_ref` column of the `run_session` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        git_sha_ref -> Nullable<Text>,
        /// The `git_commit_date` column of the `run_session` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        git_commit_date -> Nullable<Text>,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `shard_stage_update_event` table.
    ///
    /// (Automatically generated by Diesel.)
    shard_stage_update_event (rowid) {
        /// The `rowid` column of the `shard_stage_update_event` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `happened_at` column of the `shard_stage_update_event` table.
        ///
        /// Its SQL type is `Nullable<Array<_t_moment>>`.
        ///
        /// (Automatically generated by Diesel.)
        happened_at -> Nullable<SQL_Moment>,
        /// The `new_stage` column of the `shard_stage_update_event` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        new_stage -> Text,
        /// The `old_stage` column of the `shard_stage_update_event` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        old_stage -> Text,
        /// The `shard_id` column of the `shard_stage_update_event` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        shard_id -> SQL_Snowflake,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `sqlite_migration_progress` table.
    ///
    /// (Automatically generated by Diesel.)
    sqlite_migration_progress (enforce_single_row) {
        /// The `progress_counter` column of the `sqlite_migration_progress` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        progress_counter -> Int8,
        /// The `enforce_single_row` column of the `sqlite_migration_progress` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        enforce_single_row -> Bool,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `user_presence` table.
    ///
    /// (Automatically generated by Diesel.)
    user_presence (rowid) {
        /// The `rowid` column of the `user_presence` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `ready_rowid` column of the `user_presence` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        ready_rowid -> Nullable<Int8>,
        /// The `guild_rowid` column of the `user_presence` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        guild_rowid -> Nullable<Int8>,
        /// The `game` column of the `user_presence` table.
        ///
        /// Its SQL type is `Nullable<Array<_t_user_presence_game>>`.
        ///
        /// (Automatically generated by Diesel.)
        game -> Nullable<SQL_UserPresenceGame>,
        /// The `last_modified` column of the `user_presence` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        last_modified -> Nullable<Int8>,
        /// The `nick` column of the `user_presence` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        nick -> Nullable<Text>,
        /// The `status` column of the `user_presence` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Text,
        /// The `user_id` column of the `user_presence` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> SQL_Snowflake,
    }
}

table! {
    use diesel::sql_types::*;
    use crate::db_types::*;
    /// Representation of the `voice_state` table.
    ///
    /// (Automatically generated by Diesel.)
    voice_state (rowid) {
        /// The `rowid` column of the `voice_state` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rowid -> Int8,
        /// The `guild_rowid` column of the `voice_state` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_rowid -> Int8,
        /// The `channel_id` column of the `voice_state` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        channel_id -> Nullable<SQL_Snowflake>,
        /// The `deaf` column of the `voice_state` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        deaf -> Bool,
        /// The `mute` column of the `voice_state` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        mute -> Bool,
        /// The `self_deaf` column of the `voice_state` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        self_deaf -> Bool,
        /// The `self_mute` column of the `voice_state` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        self_mute -> Bool,
        /// The `session_id` column of the `voice_state` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        session_id -> Text,
        /// The `suppress` column of the `voice_state` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        suppress -> Bool,
        /// The `token` column of the `voice_state` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        token -> Nullable<Text>,
        /// The `user_id` column of the `voice_state` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> SQL_Snowflake,
    }
}

joinable!(attachment -> message (message_rowid));
joinable!(embed -> message (message_rowid));
joinable!(embed_field -> embed (embed_rowid));
joinable!(emoji -> guild (guild_rowid));
joinable!(group_channel -> ready (ready_rowid));
joinable!(guild -> guild_create_event (guild_create_event_rowid));
joinable!(guild -> ready (ready_rowid));
joinable!(guild_channel -> guild (guild_rowid));
joinable!(guild_create_event -> run_session (session_rowid));
joinable!(guild_role -> guild (guild_rowid));
joinable!(log_entry -> run_session (session_rowid));
joinable!(member -> guild (guild_rowid));
joinable!(message_archive_gets -> ready (ready_rowid));
joinable!(message_archive_gets -> run_session (session_id));
joinable!(permission_overwrite -> guild_channel (guild_channel_rowid));
joinable!(private_channel -> ready (ready_rowid));
joinable!(raw_message -> run_session (session_rowid));
joinable!(reaction -> message (message_rowid));
joinable!(user_presence -> guild (guild_rowid));
joinable!(user_presence -> ready (ready_rowid));
joinable!(voice_state -> guild (guild_rowid));

allow_tables_to_appear_in_same_query!(
    attachment,
    embed,
    embed_field,
    emoji,
    group_channel,
    guild,
    guild_channel,
    guild_create_event,
    guild_prefixes,
    guild_role,
    log_entry,
    member,
    message,
    message_archive_gets,
    migration_version,
    permission_overwrite,
    private_channel,
    raw_message,
    reaction,
    ready,
    run_session,
    shard_stage_update_event,
    sqlite_migration_progress,
    user_presence,
    voice_state,
);
